// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CertificatesColumns holds the columns for the "certificates" table.
	CertificatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "cert_pem", Type: field.TypeString, Size: 2147483647},
		{Name: "key_pem", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "desc", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "issuer_id", Type: field.TypeInt, Nullable: true},
		{Name: "usage", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "namespace_id", Type: field.TypeInt},
	}
	// CertificatesTable holds the schema information for the "certificates" table.
	CertificatesTable = &schema.Table{
		Name:       "certificates",
		Columns:    CertificatesColumns,
		PrimaryKey: []*schema.Column{CertificatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "certificates_namespaces_certificates",
				Columns:    []*schema.Column{CertificatesColumns[8]},
				RefColumns: []*schema.Column{NamespacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "certificate_namespace_id",
				Unique:  false,
				Columns: []*schema.Column{CertificatesColumns[8]},
			},
		},
	}
	// NamespacesColumns holds the columns for the "namespaces" table.
	NamespacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "desc", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// NamespacesTable holds the schema information for the "namespaces" table.
	NamespacesTable = &schema.Table{
		Name:       "namespaces",
		Columns:    NamespacesColumns,
		PrimaryKey: []*schema.Column{NamespacesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "namespace_name",
				Unique:  false,
				Columns: []*schema.Column{NamespacesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CertificatesTable,
		NamespacesTable,
	}
)

func init() {
	CertificatesTable.ForeignKeys[0].RefTable = NamespacesTable
}
