// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/logeable/certmgr/ent/certificate"
	"github.com/logeable/certmgr/ent/namespace"
	"github.com/logeable/certmgr/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	certificateFields := schema.Certificate{}.Fields()
	_ = certificateFields
	// certificateDescDesc is the schema descriptor for desc field.
	certificateDescDesc := certificateFields[4].Descriptor()
	// certificate.DefaultDesc holds the default value on creation for the desc field.
	certificate.DefaultDesc = certificateDescDesc.Default.(string)
	// certificateDescUpdatedAt is the schema descriptor for updated_at field.
	certificateDescUpdatedAt := certificateFields[6].Descriptor()
	// certificate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	certificate.DefaultUpdatedAt = certificateDescUpdatedAt.Default.(func() time.Time)
	// certificate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	certificate.UpdateDefaultUpdatedAt = certificateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// certificateDescCreatedAt is the schema descriptor for created_at field.
	certificateDescCreatedAt := certificateFields[7].Descriptor()
	// certificate.DefaultCreatedAt holds the default value on creation for the created_at field.
	certificate.DefaultCreatedAt = certificateDescCreatedAt.Default.(func() time.Time)
	// certificateDescID is the schema descriptor for id field.
	certificateDescID := certificateFields[0].Descriptor()
	// certificate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	certificate.IDValidator = certificateDescID.Validators[0].(func(int) error)
	namespaceFields := schema.Namespace{}.Fields()
	_ = namespaceFields
	// namespaceDescDesc is the schema descriptor for desc field.
	namespaceDescDesc := namespaceFields[2].Descriptor()
	// namespace.DefaultDesc holds the default value on creation for the desc field.
	namespace.DefaultDesc = namespaceDescDesc.Default.(string)
	// namespaceDescUpdatedAt is the schema descriptor for updated_at field.
	namespaceDescUpdatedAt := namespaceFields[3].Descriptor()
	// namespace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	namespace.DefaultUpdatedAt = namespaceDescUpdatedAt.Default.(func() time.Time)
	// namespace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	namespace.UpdateDefaultUpdatedAt = namespaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// namespaceDescCreatedAt is the schema descriptor for created_at field.
	namespaceDescCreatedAt := namespaceFields[4].Descriptor()
	// namespace.DefaultCreatedAt holds the default value on creation for the created_at field.
	namespace.DefaultCreatedAt = namespaceDescCreatedAt.Default.(func() time.Time)
	// namespaceDescID is the schema descriptor for id field.
	namespaceDescID := namespaceFields[0].Descriptor()
	// namespace.IDValidator is a validator for the "id" field. It is called by the builders before save.
	namespace.IDValidator = namespaceDescID.Validators[0].(func(int) error)
}
