// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/logeable/certmgr/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldID, id))
}

// NamespaceID applies equality check predicate on the "namespace_id" field. It's identical to NamespaceIDEQ.
func NamespaceID(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldNamespaceID, v))
}

// CertPem applies equality check predicate on the "cert_pem" field. It's identical to CertPemEQ.
func CertPem(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertPem, v))
}

// KeyPem applies equality check predicate on the "key_pem" field. It's identical to KeyPemEQ.
func KeyPem(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyPem, v))
}

// Desc applies equality check predicate on the "desc" field. It's identical to DescEQ.
func Desc(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldDesc, v))
}

// IssuerID applies equality check predicate on the "issuer_id" field. It's identical to IssuerIDEQ.
func IssuerID(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssuerID, v))
}

// Usage applies equality check predicate on the "usage" field. It's identical to UsageEQ.
func Usage(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUsage, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreatedAt, v))
}

// NamespaceIDEQ applies the EQ predicate on the "namespace_id" field.
func NamespaceIDEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldNamespaceID, v))
}

// NamespaceIDNEQ applies the NEQ predicate on the "namespace_id" field.
func NamespaceIDNEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldNamespaceID, v))
}

// NamespaceIDIn applies the In predicate on the "namespace_id" field.
func NamespaceIDIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldNamespaceID, vs...))
}

// NamespaceIDNotIn applies the NotIn predicate on the "namespace_id" field.
func NamespaceIDNotIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldNamespaceID, vs...))
}

// CertPemEQ applies the EQ predicate on the "cert_pem" field.
func CertPemEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertPem, v))
}

// CertPemNEQ applies the NEQ predicate on the "cert_pem" field.
func CertPemNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCertPem, v))
}

// CertPemIn applies the In predicate on the "cert_pem" field.
func CertPemIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCertPem, vs...))
}

// CertPemNotIn applies the NotIn predicate on the "cert_pem" field.
func CertPemNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCertPem, vs...))
}

// CertPemGT applies the GT predicate on the "cert_pem" field.
func CertPemGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCertPem, v))
}

// CertPemGTE applies the GTE predicate on the "cert_pem" field.
func CertPemGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCertPem, v))
}

// CertPemLT applies the LT predicate on the "cert_pem" field.
func CertPemLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCertPem, v))
}

// CertPemLTE applies the LTE predicate on the "cert_pem" field.
func CertPemLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCertPem, v))
}

// CertPemContains applies the Contains predicate on the "cert_pem" field.
func CertPemContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCertPem, v))
}

// CertPemHasPrefix applies the HasPrefix predicate on the "cert_pem" field.
func CertPemHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCertPem, v))
}

// CertPemHasSuffix applies the HasSuffix predicate on the "cert_pem" field.
func CertPemHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCertPem, v))
}

// CertPemEqualFold applies the EqualFold predicate on the "cert_pem" field.
func CertPemEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCertPem, v))
}

// CertPemContainsFold applies the ContainsFold predicate on the "cert_pem" field.
func CertPemContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCertPem, v))
}

// KeyPemEQ applies the EQ predicate on the "key_pem" field.
func KeyPemEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyPem, v))
}

// KeyPemNEQ applies the NEQ predicate on the "key_pem" field.
func KeyPemNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldKeyPem, v))
}

// KeyPemIn applies the In predicate on the "key_pem" field.
func KeyPemIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldKeyPem, vs...))
}

// KeyPemNotIn applies the NotIn predicate on the "key_pem" field.
func KeyPemNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldKeyPem, vs...))
}

// KeyPemGT applies the GT predicate on the "key_pem" field.
func KeyPemGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldKeyPem, v))
}

// KeyPemGTE applies the GTE predicate on the "key_pem" field.
func KeyPemGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldKeyPem, v))
}

// KeyPemLT applies the LT predicate on the "key_pem" field.
func KeyPemLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldKeyPem, v))
}

// KeyPemLTE applies the LTE predicate on the "key_pem" field.
func KeyPemLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldKeyPem, v))
}

// KeyPemContains applies the Contains predicate on the "key_pem" field.
func KeyPemContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldKeyPem, v))
}

// KeyPemHasPrefix applies the HasPrefix predicate on the "key_pem" field.
func KeyPemHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldKeyPem, v))
}

// KeyPemHasSuffix applies the HasSuffix predicate on the "key_pem" field.
func KeyPemHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldKeyPem, v))
}

// KeyPemIsNil applies the IsNil predicate on the "key_pem" field.
func KeyPemIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldKeyPem))
}

// KeyPemNotNil applies the NotNil predicate on the "key_pem" field.
func KeyPemNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldKeyPem))
}

// KeyPemEqualFold applies the EqualFold predicate on the "key_pem" field.
func KeyPemEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldKeyPem, v))
}

// KeyPemContainsFold applies the ContainsFold predicate on the "key_pem" field.
func KeyPemContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldKeyPem, v))
}

// DescEQ applies the EQ predicate on the "desc" field.
func DescEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldDesc, v))
}

// DescNEQ applies the NEQ predicate on the "desc" field.
func DescNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldDesc, v))
}

// DescIn applies the In predicate on the "desc" field.
func DescIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldDesc, vs...))
}

// DescNotIn applies the NotIn predicate on the "desc" field.
func DescNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldDesc, vs...))
}

// DescGT applies the GT predicate on the "desc" field.
func DescGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldDesc, v))
}

// DescGTE applies the GTE predicate on the "desc" field.
func DescGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldDesc, v))
}

// DescLT applies the LT predicate on the "desc" field.
func DescLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldDesc, v))
}

// DescLTE applies the LTE predicate on the "desc" field.
func DescLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldDesc, v))
}

// DescContains applies the Contains predicate on the "desc" field.
func DescContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldDesc, v))
}

// DescHasPrefix applies the HasPrefix predicate on the "desc" field.
func DescHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldDesc, v))
}

// DescHasSuffix applies the HasSuffix predicate on the "desc" field.
func DescHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldDesc, v))
}

// DescIsNil applies the IsNil predicate on the "desc" field.
func DescIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldDesc))
}

// DescNotNil applies the NotNil predicate on the "desc" field.
func DescNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldDesc))
}

// DescEqualFold applies the EqualFold predicate on the "desc" field.
func DescEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldDesc, v))
}

// DescContainsFold applies the ContainsFold predicate on the "desc" field.
func DescContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldDesc, v))
}

// IssuerIDEQ applies the EQ predicate on the "issuer_id" field.
func IssuerIDEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssuerID, v))
}

// IssuerIDNEQ applies the NEQ predicate on the "issuer_id" field.
func IssuerIDNEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldIssuerID, v))
}

// IssuerIDIn applies the In predicate on the "issuer_id" field.
func IssuerIDIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldIssuerID, vs...))
}

// IssuerIDNotIn applies the NotIn predicate on the "issuer_id" field.
func IssuerIDNotIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldIssuerID, vs...))
}

// IssuerIDGT applies the GT predicate on the "issuer_id" field.
func IssuerIDGT(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldIssuerID, v))
}

// IssuerIDGTE applies the GTE predicate on the "issuer_id" field.
func IssuerIDGTE(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldIssuerID, v))
}

// IssuerIDLT applies the LT predicate on the "issuer_id" field.
func IssuerIDLT(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldIssuerID, v))
}

// IssuerIDLTE applies the LTE predicate on the "issuer_id" field.
func IssuerIDLTE(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldIssuerID, v))
}

// IssuerIDIsNil applies the IsNil predicate on the "issuer_id" field.
func IssuerIDIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldIssuerID))
}

// IssuerIDNotNil applies the NotNil predicate on the "issuer_id" field.
func IssuerIDNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldIssuerID))
}

// UsageEQ applies the EQ predicate on the "usage" field.
func UsageEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUsage, v))
}

// UsageNEQ applies the NEQ predicate on the "usage" field.
func UsageNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldUsage, v))
}

// UsageIn applies the In predicate on the "usage" field.
func UsageIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldUsage, vs...))
}

// UsageNotIn applies the NotIn predicate on the "usage" field.
func UsageNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldUsage, vs...))
}

// UsageGT applies the GT predicate on the "usage" field.
func UsageGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldUsage, v))
}

// UsageGTE applies the GTE predicate on the "usage" field.
func UsageGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldUsage, v))
}

// UsageLT applies the LT predicate on the "usage" field.
func UsageLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldUsage, v))
}

// UsageLTE applies the LTE predicate on the "usage" field.
func UsageLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldUsage, v))
}

// UsageContains applies the Contains predicate on the "usage" field.
func UsageContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldUsage, v))
}

// UsageHasPrefix applies the HasPrefix predicate on the "usage" field.
func UsageHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldUsage, v))
}

// UsageHasSuffix applies the HasSuffix predicate on the "usage" field.
func UsageHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldUsage, v))
}

// UsageIsNil applies the IsNil predicate on the "usage" field.
func UsageIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldUsage))
}

// UsageNotNil applies the NotNil predicate on the "usage" field.
func UsageNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldUsage))
}

// UsageEqualFold applies the EqualFold predicate on the "usage" field.
func UsageEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldUsage, v))
}

// UsageContainsFold applies the ContainsFold predicate on the "usage" field.
func UsageContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldUsage, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCreatedAt, v))
}

// HasNamespace applies the HasEdge predicate on the "namespace" edge.
func HasNamespace() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NamespaceTable, NamespaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNamespaceWith applies the HasEdge predicate on the "namespace" edge with a given conditions (other predicates).
func HasNamespaceWith(preds ...predicate.Namespace) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newNamespaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.NotPredicates(p))
}
